### ISSUE TITLE
[bug] Ultimine not working with better default biomes enchantment

### ISSUE THREAD

**Issue by Hautzii** [FTBTeam/FTB-Ultimine#85] opened 2021-07-06 18:25 UTC
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**

Ultimine : 1605.2.2-build.4
Better default biomes : Alpha 2.5.3

**Forge / Fabric version, if applicable**

36.1.0

**Modpack (with version), if applicable**

**If the issue is a crash; An external link to the crash report**

**How to reproduce the issue**
*Please provide use with a step by step description*

Install the better default biomes mod and the ultimine mod. Enchant a pickaxe with smelting touch. Ultimine stops working with every ore that needs to be smelted. I'm on a custom modpack but played with the same two mods in the "life in the village 2" modpack and couldn't reproduce the issue. I checked the config files but can't see anything about the smelting touch enchant.

**A screenshot, if applicable**

**Anything else we should know?**

Ultimine does work with the smelting touch enchant if the ore doesn't need to be smelted. The hunger for the whole vein is still consumed even if I break only one block at a time.

**Comment by MaxNeedsSnacks** [comment] 2021-07-19 23:03
Duplicate of https://github.com/Xratedjunior/Better-Default-Biomes/issues/12

**Closed by MaxNeedsSnacks** 2021-07-19 23:03 UTC

**Comment by MaxNeedsSnacks** [comment] 2021-07-19 23:04
Unfortunately, I can't really debug this issue on our end either since BDB is closed-source and All Rights Reserved, but they're probably listening to the block break event at a higher priority than we are and then cancelling it, so Ultimine doesn't get a chance to actually apply its own effects
